# Generated by Django 3.1.5 on 2021-02-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Targets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('currency', models.CharField(max_length=20)),
                ('fundType', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=30)),
                ('partition', models.CharField(max_length=20)),
                ('dividendFrequency', models.CharField(max_length=10)),
                ('url', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=20)),
            ],
        ),
    ]
