# Generated by Django 3.1.5 on 2021-02-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivers',
            name='lineToken',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
